dependencies {
    api libs.bundles.poi
    implementation libs.javassist

    testImplementation libs.bundles.log4j2
    // https://central.sonatype.com/artifact/com.alibaba/easyexcel
    testImplementation 'com.alibaba:easyexcel:4.0.3'
    // https://central.sonatype.com/artifact/com.opencsv/opencsv
    testImplementation 'com.opencsv:opencsv:5.12.0'
}
