plugins {
    // https://plugins.gradle.org/plugin/org.springframework.boot
    id 'org.springframework.boot' version '2.7.12' apply false
    // https://plugins.gradle.org/plugin/io.spring.dependency-management
    id 'io.spring.dependency-management' version '1.1.0' apply false
}

subprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }
    }

    apply plugin: 'java-library'
    compileJava.options.encoding = 'UTF-8'
    compileTestJava.options.encoding = 'UTF-8'
    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    version = VERSION
    group = GROUP_ID

    dependencies {
        compileOnly libs.lombok
        annotationProcessor libs.lombok
        testCompileOnly libs.lombok
        testAnnotationProcessor libs.lombok
        implementation libs.slf4j.api
        testImplementation libs.jupiter.api
        testRuntimeOnly libs.jupiter.engine

        implementation libs.dreamcat.common

        testImplementation libs.bundles.jackson
        // https://mvnrepository.com/artifact/org.javassist/javassist
        testImplementation "org.javassist:javassist:3.30.2-GA"
    }

    test {
        useJUnitPlatform()
    }
}
