# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
[versions]
dreamcat = "0.5-SNAPSHOT"
# https://mvnrepository.com/artifact/org.projectlombok/lombok
lombok = '1.18.30'
# https://mvnrepository.com/artifact/org.slf4j/slf4j-api
slf4j = '1.7.36'
# https://central.sonatype.com/artifact/org.junit.jupiter/junit-jupiter-api
jupiter = '5.9.2'
# https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
jackson = "2.17.2"
# https://mvnrepository.com/artifact/org.apache.poi/poi
poi = "5.3.0"
# https://mvnrepository.com/artifact/com.google.zxing/core
zxing = "3.5.1"
# https://mvnrepository.com/artifact/co.elastic.clients/elasticsearch-java
elasticsearch = "8.8.1"

[libraries]
dreamcat-common = { module = "org.dreamcat:common", version.ref = "dreamcat" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
poi = { module = "org.apache.poi:poi", version.ref = "poi"}
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi"}
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing"}
zxing-javase = { module = "com.google.zxing:javase", version.ref = "zxing"}
elasticsearch-java = { module = "co.elastic.clients:elasticsearch-java", version.ref = "elasticsearch"}

[bundles]
jackson = ["jackson-databind", "jackson-annotations"]
poi = ["poi", "poi-ooxml"]
zxing = ["zxing-core", "zxing-javase"]
