GET {{origin}}/data/animal
Accept: application/json

###

DELETE {{origin}}/data/animal
Accept: application/json

###

###
POST {{origin}}/data/animal
Content-Type: application/json

[
  {
    "name": "name",
    "type": "text",
    "analyzer": "ngram_analyzer",
    "keyword": true
  },
  {
    "name": "code",
    "type": "keyword"
  },
  {
    "name": "title",
    "type": "text",
    "analyzer": "ngram_analyzer"
  },
  {
    "name": "age",
    "type": "integer"
  },
  {
    "name": "shoe_size",
    "type": "long"
  },
  {
    "name": "weight",
    "type": "scaled_float",
    "scalingFactor": 10000
  },
  {
    "name": "birthday",
    "type": "date",
    "dateFormat": "yyyy-MM-dd HH:mm"
  },
  {
    "name": "foot",
    "type": "nested",
    "children": [
      {
        "name": "color",
        "type": "keyword"
      },
      {
        "name": "toes",
        "type": "nested",
        "children": [
          {
            "name": "color",
            "type": "text",
            "analyzer": "ngram_analyzer",
            "keyword": true
          },
          {
            "name": "count",
            "type": "byte"
          }
        ]
      },
      {
        "name": "mark",
        "type": "keyword"
      }
    ]
  },
  {
    "name": "color",
    "type": "keyword"
  }
]
