dependencies {
    implementation libs.jackson.annotations
    implementation libs.jackson.databind

    // web framework
    compileOnly libs.spring.web
    compileOnly libs.spring.webmvc
    compileOnly libs.spring.webflux
    compileOnly libs.spring.context
    compileOnly libs.spring.boot.autoconfigure
    compileOnly libs.spring.security.core
    compileOnly libs.spring.security.config
    compileOnly libs.spring.security.web

    // other
    compileOnly libs.servlet
    compileOnly libs.jpa
    compileOnly libs.mybatis
    compileOnly libs.aspectj.weaver
}

apply from: new File(rootDir, 'gradle/publish.gradle')
